# Generated by Django 3.2.10 on 2022-04-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbuyer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
