# Generated by Django 3.2.10 on 2022-03-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbuyer',
            name='Condition',
            field=models.CharField(default='Good', max_length=10),
        ),
        migrations.AddField(
            model_name='carbuyer',
            name='asking_pricce',
            field=models.FloatField(default=15000, max_length=7),
        ),
        migrations.AddField(
            model_name='carbuyer',
            name='make',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbuyer',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbuyer',
            name='year',
            field=models.IntegerField(default=2022, max_length=4),
        ),
    ]
