# Generated by Django 3.2.10 on 2022-03-30 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_buyer', '0002_auto_20220329_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbuyer',
            name='user_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carbuyer',
            name='asking_pricce',
            field=models.FloatField(default=15000),
        ),
        migrations.AlterField(
            model_name='carbuyer',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
