# Generated by Django 3.2.10 on 2022-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_buyer', '0002_alter_carbuyer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbuyer',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
