# Generated by Django 3.2.10 on 2022-04-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_buyer', '0005_carbuyer_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbuyer',
            name='user_id',
        ),
    ]
