# Generated by Django 3.2.10 on 2022-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_seller', '0005_alter_carseller_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carseller',
            name='year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2022, max_length=4, verbose_name='year'),
        ),
    ]
