# Generated by Django 3.2.10 on 2022-03-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_seller', '0006_alter_carseller_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carseller',
            name='Condition',
            field=models.CharField(choices=[('Poor', 'poor'), ('Fair', 'fair'), ('Good', 'good'), ('Eexcellent', 'excellent')], max_length=10),
        ),
    ]
