# Generated by Django 3.2.10 on 2022-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_seller', '0009_alter_carseller_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carseller',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
