# Generated by Django 3.2.10 on 2022-03-29 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_seller', '0011_carseller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carseller',
            name='asking_pricce',
            field=models.FloatField(max_length=7, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1500)]),
        ),
    ]
