# Generated by Django 3.2.10 on 2022-03-30 04:03

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('car_seller', '0018_auto_20220330_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carseller',
            name='asking_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(1000), djmoney.models.validators.MaxMoneyValidator(100000)]),
        ),
    ]
